export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED';
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';

export const TRANSFER_FUNDS = 'TRANSFER_FUNDS';
export const TRANSFER_FUNDS_FAILED = 'TRANSFER_FUNDS_FAILED';

export const SET_API_TOKEN = 'SET_API_TOKEN';
export const UNSET_API_TOKEN = 'UNSET_API_TOKEN';

