export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED';
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const PURGE_TRANSACTIONS = 'PURGE_TRANSACTIONS';

export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_FAILED = 'ACCOUNTS_FAILED';
export const ADD_ACCOUNTS = 'ADD_ACCOUNTS';
export const PURGE_ACCOUNTS = 'PURGE_ACCOUNTS';

export const TRANSFER_FUNDS = 'TRANSFER_FUNDS';
export const TRANSFER_FUNDS_FAILED = 'TRANSFER_FUNDS_FAILED';

export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const CLEAR_AUTH_DATA = 'CLEAR_AUTH_DATA';

export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
export const ADD_USER_DATA = 'ADD_USER_DATA';
export const PURGE_USER_DATA = 'PURGE_USER_DATA';

export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_REGISTER_MODAL = 'TOGGLE_REGISTER_MODAL';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTRATION_STARTED = 'REGISTRATION_STARTED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';